export const ACTIVITY_ACTIONS = {
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGIN_FAILED: 'auth.login_failed',
  AUTH_LOGOUT: 'auth.logout',
  COUNSELLOR_CREATED: 'counsellor.created',
  COUNSELLOR_UPDATED: 'counsellor.updated',
  COUNSELLOR_STATUS_CHANGED: 'counsellor.status_changed',
  COUNSELLOR_DELETED: 'counsellor.deleted',
  COUNSELLOR_PROFILE_IMAGE_UPDATED: 'counsellor.profile_image_updated',
  SPECIALIZATION_CREATED: 'specialization.created',
  SPECIALIZATION_DEACTIVATED: 'specialization.deactivated',
  SPECIALIZATION_PERMANENTLY_DELETED: 'specialization.permanently_deleted',
  AVAILABILITY_CREATED: 'availability.created',
  AVAILABILITY_RECURRING_CREATED: 'availability.recurring_created',
  AVAILABILITY_BLOCKED: 'availability.blocked',
  AVAILABILITY_UPDATED: 'availability.updated',
  AVAILABILITY_DELETED: 'availability.deleted',
  BOOKING_CREATED: 'booking.created',
  BOOKING_STATUS_CHANGED: 'booking.status_changed',
  BOOKING_RESCHEDULED: 'booking.rescheduled',
  ADMIN_USER_CREATED: 'admin_user.created',
  ADMIN_USER_UPDATED: 'admin_user.updated',
  ADMIN_USER_STATUS_CHANGED: 'admin_user.status_changed',
  ADMIN_USER_DELETED: 'admin_user.deleted',
  ADMIN_ROLE_CREATED: 'admin_role.created',
  PSYCHOMETRIC_VIEWED: 'psychometric.viewed',
  SCHOOL_MOU_CREATED: 'school_mou.created',
  SCHOOL_MOU_UPDATED: 'school_mou.updated',
  SCHOOL_MOU_STATUS_CHANGED: 'school_mou.status_changed',
  SCHOOL_MOU_DELETED: 'school_mou.deleted',
  ELIBRARY_CREATED: 'elibrary.created',
  ELIBRARY_UPDATED: 'elibrary.updated',
  ELIBRARY_STATUS_CHANGED: 'elibrary.status_changed',
  ELIBRARY_DELETED: 'elibrary.deleted',
  ELIBRARY_CATEGORY_CREATED: 'elibrary.category_created',
  ELIBRARY_CATEGORY_STATUS_CHANGED: 'elibrary.category_status_changed',
  ELIBRARY_CATEGORY_DELETED: 'elibrary.category_deleted',
  ELIBRARY_LANGUAGE_CREATED: 'elibrary.language_created',
  ELIBRARY_LANGUAGE_STATUS_CHANGED: 'elibrary.language_status_changed',
  ELIBRARY_LANGUAGE_DELETED: 'elibrary.language_deleted',
};

export const ACTIVITY_ACTION_LABELS = {
  [ACTIVITY_ACTIONS.AUTH_LOGIN]: 'Signed in',
  [ACTIVITY_ACTIONS.AUTH_LOGIN_FAILED]: 'Failed sign in',
  [ACTIVITY_ACTIONS.AUTH_LOGOUT]: 'Signed out',
  [ACTIVITY_ACTIONS.COUNSELLOR_CREATED]: 'Counsellor created',
  [ACTIVITY_ACTIONS.COUNSELLOR_UPDATED]: 'Counsellor updated',
  [ACTIVITY_ACTIONS.COUNSELLOR_STATUS_CHANGED]: 'Counsellor status changed',
  [ACTIVITY_ACTIONS.COUNSELLOR_DELETED]: 'Counsellor deleted',
  [ACTIVITY_ACTIONS.COUNSELLOR_PROFILE_IMAGE_UPDATED]: 'Profile image updated',
  [ACTIVITY_ACTIONS.SPECIALIZATION_CREATED]: 'Specialization created',
  [ACTIVITY_ACTIONS.SPECIALIZATION_DEACTIVATED]: 'Specialization deactivated',
  [ACTIVITY_ACTIONS.SPECIALIZATION_PERMANENTLY_DELETED]: 'Specialization permanently deleted',
  [ACTIVITY_ACTIONS.AVAILABILITY_CREATED]: 'Availability added',
  [ACTIVITY_ACTIONS.AVAILABILITY_RECURRING_CREATED]: 'Recurring availability added',
  [ACTIVITY_ACTIONS.AVAILABILITY_BLOCKED]: 'Dates blocked',
  [ACTIVITY_ACTIONS.AVAILABILITY_UPDATED]: 'Availability updated',
  [ACTIVITY_ACTIONS.AVAILABILITY_DELETED]: 'Availability removed',
  [ACTIVITY_ACTIONS.BOOKING_CREATED]: 'Booking created',
  [ACTIVITY_ACTIONS.BOOKING_STATUS_CHANGED]: 'Booking status changed',
  [ACTIVITY_ACTIONS.BOOKING_RESCHEDULED]: 'Booking rescheduled',
  [ACTIVITY_ACTIONS.ADMIN_USER_CREATED]: 'Admin user created',
  [ACTIVITY_ACTIONS.ADMIN_USER_UPDATED]: 'Admin user updated',
  [ACTIVITY_ACTIONS.ADMIN_USER_STATUS_CHANGED]: 'Admin user status changed',
  [ACTIVITY_ACTIONS.ADMIN_USER_DELETED]: 'Admin user deactivated',
  [ACTIVITY_ACTIONS.ADMIN_ROLE_CREATED]: 'Role created',
  [ACTIVITY_ACTIONS.PSYCHOMETRIC_VIEWED]: 'Psychometric report viewed',
  [ACTIVITY_ACTIONS.SCHOOL_MOU_CREATED]: 'School MOU created',
  [ACTIVITY_ACTIONS.SCHOOL_MOU_UPDATED]: 'School MOU updated',
  [ACTIVITY_ACTIONS.SCHOOL_MOU_STATUS_CHANGED]: 'School MOU status changed',
  [ACTIVITY_ACTIONS.SCHOOL_MOU_DELETED]: 'School MOU deleted',
  [ACTIVITY_ACTIONS.ELIBRARY_CREATED]: 'E-library document uploaded',
  [ACTIVITY_ACTIONS.ELIBRARY_UPDATED]: 'E-library document updated',
  [ACTIVITY_ACTIONS.ELIBRARY_STATUS_CHANGED]: 'E-library document status changed',
  [ACTIVITY_ACTIONS.ELIBRARY_DELETED]: 'E-library document deleted',
  [ACTIVITY_ACTIONS.ELIBRARY_CATEGORY_CREATED]: 'E-library category added',
  [ACTIVITY_ACTIONS.ELIBRARY_CATEGORY_STATUS_CHANGED]: 'E-library category status changed',
  [ACTIVITY_ACTIONS.ELIBRARY_CATEGORY_DELETED]: 'E-library category deleted',
  [ACTIVITY_ACTIONS.ELIBRARY_LANGUAGE_CREATED]: 'E-library language added',
  [ACTIVITY_ACTIONS.ELIBRARY_LANGUAGE_STATUS_CHANGED]: 'E-library language status changed',
  [ACTIVITY_ACTIONS.ELIBRARY_LANGUAGE_DELETED]: 'E-library language deleted',
};

export const ACTIVITY_ACTION_OPTIONS = Object.entries(ACTIVITY_ACTION_LABELS).map(([value, label]) => ({
  value,
  label,
}));
